In [1]:
#import numpy
import numpy as np

In [16]:
#create array
a=np.array([1,2,3,4,7])
b=np.array([2,3,5])
print(a)
print(b)

[1 2 3 4 7]
[2 3 5]


In [3]:

print("shape of a is:{}".format(a.shape)) # Shape of array: It is used find the dimensional shape of the array

shape of a is:(5,)


In [5]:
print("dim of array is {}".format(a.ndim)) # Dimension of array: Returns an integer that tells us how many dimensions the array have.

dim of array is 1


In [6]:
print("size of a is {}".format(a.size)) # Size: Return the size of the array

size of a is 5


In [7]:
print(f"data type of a {a.dtype}") # dtype: Return the datatype of the array

data type of a int64


In [8]:
print(f"itemsize {a.itemsize}") # itemsize : The element size of this data-type object

itemsize 8


In [9]:
print(f"data {a.data}") #data memory location

data <memory at 0x7fc12087c640>


In [13]:
# Matrix Multiplication
a1=np.array([[1,2],[4,5]])
b1=np.array([[9,8],[6,5]])
print(a1)
print(b1)


[[1 2]
 [4 5]]
[[9 8]
 [6 5]]


In [14]:
mul=np.dot(a1,b1) # dot: Return the multiplication of the matrix
print(mul)


[[21 18]
 [66 57]]


In [18]:
print(a.sum()) # sum: sum of all elements of array

17


In [19]:
a2=np.array([[1,2,3],[4,5,6]])
b2=np.array([[9,8,7],[6,5,4]])
print(a2)
print(b2)


[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]]


In [20]:
sliced_arr=a2[1:,1:] # slice of array
print(sliced_arr)


[[5 6]]


In [21]:
addm=np.add(a1,b1)# add: will add two or more arrays
print(addm)

[[10 10]
 [10 10]]


In [22]:
subm=np.subtract(a1,b1)# subtract : will subtract arrays
print(subm)

[[-8 -6]
 [-2  0]]


In [23]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(c)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [24]:
re=c.reshape(4,4)# reshape : shape the array according to our choice
print(re)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [25]:
print("maximum in c is",c.max()) # max : maximum element from the array
print("minimum in c is",c.min()) # min : minimum element from the array
print("maximum in row is",re.max(axis=1))# axis=1 : maximum of array of a row
print("minimum in column is",re.min(axis=0))# axis=0 : maximum of array of a column


maximum in c is 16
minimum in c is 1
maximum in row is [ 4  8 12 16]
minimum in row is [1 2 3 4]


In [26]:
d=np.array([[4,8,25],[36,49,64]])
print(d)


[[ 4  8 25]
 [36 49 64]]


In [27]:
print(np.sqrt(d)) # sqrt: square root of all element
print("sd",np.std(d)) # std: calculates the standard deviation of given data along a specified axis.

[[2.         2.82842712 5.        ]
 [6.         7.         8.        ]]
sd 21.33854103103896


In [41]:
a3=np.array([[2,3],[5,6]])
print(a3)
b3=np.array([[4,8],[9,7]])
print(b3)

v=np.vstack((a3,b3)) #vstack: merge two array vertically
print(v)
h=np.hstack((a3,b3)) #hstack: merge two array horizontally
print(h)
vNew=np.vsplit(v,2) # split vertically merged array
print(vNew)
hNew=np.hsplit(v,2) # split horizontally merged array
print(hNew)


[[2 3]
 [5 6]]
[[4 8]
 [9 7]]
[[2 3]
 [5 6]
 [4 8]
 [9 7]]
[[2 3 4 8]
 [5 6 9 7]]
[array([[2, 3],
       [5, 6]]), array([[4, 8],
       [9, 7]])]
[array([[2],
       [5],
       [4],
       [9]]), array([[3],
       [6],
       [8],
       [7]])]


In [35]:
arr=np.arange(1,20,2) #arange: function that print array from 1 to 20 with gap of 2
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
arr1=np.arange(0,100,5)
print(arr1)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [37]:
arr2=np.linspace(0,20,5) # same as arange but default in float
print(arr2)
print(arr2.dtype)

[ 0.  5. 10. 15. 20.]
float64


In [45]:
ar=np.array([[25,64,34],[89,36,89]])
print(ar)
dt=ar.T # return transpose of array
print(dt)

[[25 64 34]
 [89 36 89]]
[[25 89]
 [64 36]
 [34 89]]


In [46]:
for i in np.nditer(dt): # iterate all element one by one
    print("element",i)

element 25
element 64
element 34
element 89
element 36
element 89


In [47]:
Fun=np.array([32,43,87,90])
print(Fun)

[32 43 87 90]


In [59]:
print("Square root : ",np.sqrt(Fun)) # square root of element

Square root :  [5.65685425 6.55743852 9.32737905 9.48683298]


In [61]:
print("Standard Deviation: ",np.std(arr))     # Returns the standard deviation of in the array

Standard Deviation:  5.744562646538029


In [57]:
print("Exponentials: ",np.exp(Fun))     # exponentials of element

Exponentials:  [7.89629602e+13 4.72783947e+18 6.07603023e+37 1.22040329e+39]


In [53]:
print("Sum of all element in array: ",np.sum(Fun))     # sum of all elements in the array

Sum of all element in array:  252


In [54]:
print("Sin of each element: ",np.sin(Fun))     # Returns  sin of each element

Sin of each element:  [ 0.55142668 -0.83177474 -0.82181784  0.89399666]


In [55]:
print("Cos of each element: ",np.cos(Fun))     # Returns the cosine of each element

Cos of each element:  [ 0.83422336  0.5551133   0.56975033 -0.44807362]


In [62]:
print("Log: ",np.log(Fun))     # Returns the logarithm of each element

Log:  [3.4657359  3.76120012 4.46590812 4.49980967]


In [64]:
from scipy import stats as st
print("Mean:",np.mean(Fun)) # mean of array

Mean: 63.0


In [66]:
print("Median:",np.median(Fun) # median of array

Median: 65.0


In [70]:
Fun1=np.array([90,90,32,43,87,90])
print(Fun1)
print("Mode:",st.mode(Fun1)) # mode of array

[90 90 32 43 87 90]
Mode: ModeResult(mode=array([90]), count=array([3]))
